# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Kenneth Baldauf
tagline:          'kbaldauf'
description:      'puts "Hello World!"'
url:              http://kbaldauf.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Kenneth Baldauf'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/kbaldauf/kbaldauf.github.io
